[bumpver]
current_version = "v56.2.1"
version_pattern = "vMAJOR.MINOR.PATCH[-TAG.NUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"CMakeLists.txt" = [
  'set(ADCIRC_VERSION_STRING "{version}")',
]
"README.md" = [
  "docker/v/adcircorg/adcirc/{version}?"
]
